# Generated by Django 3.1.2 on 2020-10-23 16:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lead',
            managers=[
                ('lead_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
